<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OK</name>
   <tag></tag>
   <elementGuidId>3b90395a-58e5-419a-b3bd-c4699aeb5cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.SFC.SourceCode-Forms-Controls-Web-Button.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupWin_39c44aa7-6fa0-366b-c899-6d24f0264597']/div[3]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e27e2a17-a738-4a4e-961e-6e7d9c291f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button button</value>
      <webElementGuid>b4bbebe3-fd4b-458c-9cfe-d48309abf2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>d27d7834-2fa6-41e0-80e3-f9c65bf0ce3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>9f9e7927-c9d9-4be4-ac52-a84253b68230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupWin_39c44aa7-6fa0-366b-c899-6d24f0264597&quot;)/div[@class=&quot;popup-footer&quot;]/div[@class=&quot;popup-footer-c&quot;]/a[@class=&quot;SFC SourceCode-Forms-Controls-Web-Button button&quot;]</value>
      <webElementGuid>bb473ea8-1336-42e7-b0ca-5d08969fb2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Complaint/Page_NBA/iframe_Application_frame-content</value>
      <webElementGuid>9f1df0e2-2fac-4e79-b523-38ff54b782e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_39c44aa7-6fa0-366b-c899-6d24f0264597']/div[3]/div[2]/a</value>
      <webElementGuid>a4d04778-6ce3-4108-b5de-deb997c788e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'OK')]</value>
      <webElementGuid>2fb34a23-2901-4694-b184-76d2ff34100c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CMP/2023/105'])[2]/following::a[1]</value>
      <webElementGuid>3268f895-f0c1-4de4-9f38-bd82bdafda99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>8addd661-30d0-4ccd-a2fa-532f7e73cc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>5295f72e-b008-497e-8355-082f364dee32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[96]</value>
      <webElementGuid>f44cf68d-e251-49a1-89cd-20dd203a434b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>68a882f0-25dd-4596-9362-d29b4da4ab62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>89b01d9c-dd00-4d4a-b057-88aab7eb6dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
