<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit</name>
   <tag></tag>
   <elementGuidId>911c0055-b376-43bf-ab89-e9f5e2620073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7b919e55-a8ca-5d90-ad25-986855773ac3_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='7b919e55-a8ca-5d90-ad25-986855773ac3_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>649492bc-7176-471f-9821-e544aa1b893e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7b919e55-a8ca-5d90-ad25-986855773ac3_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      <webElementGuid>4accb049-decf-4791-b732-d7f22c642942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.submit</value>
      <webElementGuid>05f848ae-c6a7-41db-929d-66160e05746d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button visible</value>
      <webElementGuid>4375c23d-70a6-4b59-a9b9-9b5b6e032ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>eff3685b-f9dd-4f52-8cb9-be64fb43bda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b11e9daf-7e43-4d80-ba22-61dfa6c65248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isvisible&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;\u003e\u003cMargin\u003e\u003cDefault\u003e3px\u003c/Default\u003e\u003c/Margin\u003e\u003c/Style\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>f640a4b3-96bf-4158-89c1-5767032f31c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>5f4302af-4ae4-4c9d-a434-228990b3a9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7b919e55-a8ca-5d90-ad25-986855773ac3_286725f8-ee17-3bc5-6142-b060c4031e85&quot;)</value>
      <webElementGuid>2c6738b8-9aa2-4d36-a52e-d58c545cd02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Complaint/Page_NBA/iframe_Application_frame-content</value>
      <webElementGuid>b43c91c3-a4a1-49a7-8ea2-e1d20a187e9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='7b919e55-a8ca-5d90-ad25-986855773ac3_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      <webElementGuid>d95480f2-cedc-4ca1-a9ce-1e282d21841f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='1efff9ff-d3c3-61aa-b430-98ff6200bd23']/a</value>
      <webElementGuid>7e9909cc-7cd3-4b13-9bf6-764fa07b4327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Submit')]</value>
      <webElementGuid>204f124f-f1a4-45a7-8649-19fafb6b11db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::a[2]</value>
      <webElementGuid>fb599b7c-9ea3-4784-a88d-90c0fc624e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acknowledgment'])[1]/following::a[2]</value>
      <webElementGuid>ad6cb19b-9e8f-4645-a6b6-963a27f37212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[3]/preceding::a[4]</value>
      <webElementGuid>67911099-3520-418d-94a1-18fa094e6495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All fields'])[5]/preceding::a[5]</value>
      <webElementGuid>530a4c52-e309-4f12-8e35-c431ddcfa0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>2acf18f6-6a2d-441f-ae54-840350c8bb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>92aef304-fa3c-492a-acd1-35ec17b0cb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>7f5e81ef-aab4-44a0-8476-47f42540be98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '7b919e55-a8ca-5d90-ad25-986855773ac3_286725f8-ee17-3bc5-6142-b060c4031e85' and @name = 'btn.submit' and @href = '#' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>e4c1a7bb-9e22-49d1-b3c8-d62747a3b698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
