<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alpha Bet</name>
   <tag></tag>
   <elementGuidId>f4225b2d-d060-4b21-877c-141f0193ba13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Alpha Bet' or . = ' Alpha Bet') and @ref_element = 'Object Repository/NBA/Complaint/Page_NBA/iframe_Application_frame-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.hoverdiv.option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='f64889d3-e4c3-2606-23e0-ab1e6d4c0ebc_2b7f370b-8b82-4738-8193-b43e25332670']/div[2]/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab5e1fba-3569-46c8-bb02-6c69c620d6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea6e543a-a98a-4a1e-b36f-26bcc7ff2b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1428</value>
      <webElementGuid>759bece4-7735-4c56-a36c-f9ed46c94412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9cb70bf5-cdb0-41ec-8653-010379da9a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hoverdiv option</value>
      <webElementGuid>d894dc3a-acdc-442f-81b1-dbd741d46c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Alpha Bet</value>
      <webElementGuid>a6f23b4a-0315-4e70-9ee4-49a64035fff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f64889d3-e4c3-2606-23e0-ab1e6d4c0ebc_2b7f370b-8b82-4738-8193-b43e25332670&quot;)/div[@class=&quot;stylewrapper&quot;]/div[@class=&quot;selectWrapper noHeader&quot;]/div[@class=&quot;listBoxSelect select selectPosition&quot;]/div[@class=&quot;listwrapper&quot;]/div[@class=&quot;optionwrapper&quot;]/div[@class=&quot;hoverdiv option&quot;]</value>
      <webElementGuid>dac5a9a6-1ce6-4802-87ae-b9fdc33ea381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Complaint/Page_NBA/iframe_Application_frame-content</value>
      <webElementGuid>5a93c4e2-d7da-43b4-a327-1061614bfedc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f64889d3-e4c3-2606-23e0-ab1e6d4c0ebc_2b7f370b-8b82-4738-8193-b43e25332670']/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>b143f264-b71e-4324-a696-298702d9c0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[2]/following::div[7]</value>
      <webElementGuid>cc789a76-7c7c-429c-9cf5-7df163cff078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[1]/following::div[14]</value>
      <webElementGuid>45642395-d9a0-4645-857c-bddb806cb2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AR Representative Company'])[1]/preceding::div[1]</value>
      <webElementGuid>57cfb60e-ba6f-47ec-b1b9-c85377e55a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ariba'])[1]/preceding::div[2]</value>
      <webElementGuid>9d75cab9-e386-4513-b315-26cce9e8ff9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alpha Bet']/parent::*</value>
      <webElementGuid>765b1b84-66e0-4e1e-af59-be3392b3beb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>1e8a998e-87fe-41e7-bb40-741c4a81bb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Alpha Bet' or . = ' Alpha Bet')]</value>
      <webElementGuid>0f9a979b-3dad-432b-b9d9-cef5b9ef5156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
