<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Application_frame-content</name>
   <tag></tag>
   <elementGuidId>8b5f7c96-f71c-4387-8fa3-ff51504de34e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.frame-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>64df23f4-d43c-4ccb-a0b2-3bdf7612664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>fbd95b62-4e89-4779-8a8e-6eb76a25d104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frame-content</value>
      <webElementGuid>170eed4f-7fa3-4c31-af84-ec23dad8da2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Complaint.External/?pLanguage=en-US&amp;pBusinessEntityId=454&amp;pUserName=Pan11&amp;pActingAs=PROFILE</value>
      <webElementGuid>30e31945-c7df-45b2-9388-ab6588b9a938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fe0ef513-e9ea-4d2c-a327-a9849d77103e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;rc-scrollbars-container sc-hAZoDl eayMnQ&quot;]/div[@class=&quot;rc-scrollbars-view&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;sc-kLLXSd gXmLNb frame-container&quot;]/iframe[@class=&quot;frame-content&quot;]</value>
      <webElementGuid>b863db52-79f0-4175-924e-15a8a3272271</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='']</value>
      <webElementGuid>1b7b7084-72c8-40e5-b942-da2f340d2239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/section/main/section/main/div/div/iframe</value>
      <webElementGuid>84fde1a4-1e67-4ecf-b962-0cdc045ca867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0de59531-a183-4a7f-b221-3d35d8c6fb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Application' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Complaint.External/?pLanguage=en-US&amp;pBusinessEntityId=454&amp;pUserName=Pan11&amp;pActingAs=PROFILE']</value>
      <webElementGuid>899bdbd7-cc6c-4efb-9f91-7bbdd6dfee3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
