<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Online Betting</name>
   <tag></tag>
   <elementGuidId>522976bc-62f2-48f6-b3b6-f64600707929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f64889d3-e4c3-2606-23e0-ab1e6d4c0ebc_02fcc089-3e62-4f97-b8a5-1159ba3d257c_droplist > div.drop-menu-m > div.drop-menu-m-c > div.drop-menu-wrapper > ul.drop-menu > li:nth-of-type(3) > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='f64889d3-e4c3-2606-23e0-ab1e6d4c0ebc_02fcc089-3e62-4f97-b8a5-1159ba3d257c_droplist']/div[2]/div[2]/div/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>430b75be-2f9b-4b65-a08d-6cc284cc1c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Online Betting</value>
      <webElementGuid>da986c74-aad9-4d68-a1ab-48aa0416c10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f64889d3-e4c3-2606-23e0-ab1e6d4c0ebc_02fcc089-3e62-4f97-b8a5-1159ba3d257c_droplist&quot;)/div[@class=&quot;drop-menu-m&quot;]/div[@class=&quot;drop-menu-m-c&quot;]/div[@class=&quot;drop-menu-wrapper&quot;]/ul[@class=&quot;drop-menu&quot;]/li[3]/a[1]/span[1]</value>
      <webElementGuid>ff0d0f78-1efe-4cd6-ba2c-3430212f2955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Complaint/Page_NBA/iframe_Application_frame-content</value>
      <webElementGuid>246ded0d-5036-4f26-97f6-5f031c46db7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f64889d3-e4c3-2606-23e0-ab1e6d4c0ebc_02fcc089-3e62-4f97-b8a5-1159ba3d257c_droplist']/div[2]/div[2]/div/ul/li[3]/a/span</value>
      <webElementGuid>78088b1c-f680-4926-9d20-321bc750b00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Betting'])[1]/following::span[1]</value>
      <webElementGuid>055ed3f0-690a-47c1-b94b-eb19e5f92a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[4]/preceding::span[1]</value>
      <webElementGuid>7749fba7-9aee-4ddd-9383-a88531891096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Online Betting']/parent::*</value>
      <webElementGuid>5fc75e22-0d63-4b2a-8047-f31b8078f332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div[2]/div/ul/li[3]/a/span</value>
      <webElementGuid>c2dc4fa6-e383-48af-b793-771ae92daddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Online Betting' or . = 'Online Betting')]</value>
      <webElementGuid>5e50d4e5-a3fb-4ffc-8f17-d2823dd64026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
