<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit</name>
   <tag></tag>
   <elementGuidId>5cf01c35-6a13-4bf8-9063-4961885db053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>639d2c88-2bb3-48d4-a2eb-24bb9ca2a12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      <webElementGuid>90d99c40-2ac4-4a60-85bb-875ff76fb063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.submit</value>
      <webElementGuid>8199d0c9-565d-4028-aaeb-9e73cb34f11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button visible</value>
      <webElementGuid>461235ef-8b07-4ad3-8c12-943d7332177a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d526fcd9-99c3-49e3-9fcd-e49ef097926f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5723dcb-1a50-448a-ac00-639f20628517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isvisible&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;\u003e\u003cMargin\u003e\u003cDefault\u003e3px\u003c/Default\u003e\u003c/Margin\u003e\u003c/Style\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>af137c80-e9a3-4184-b37f-5f367d123223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>06ce56cc-e312-44a9-8226-404b59015dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85&quot;)</value>
      <webElementGuid>2cfb9098-7a54-415c-9a99-d19258ce5143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contact Us Registered/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>1e1b7e5e-4a37-47e3-aa21-0cbb694077e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      <webElementGuid>ba5cf896-add9-4955-bf5a-3cad4f14fcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='9aafc93d-8cb2-faab-3d58-4f5290db741d']/a</value>
      <webElementGuid>4ee70ec3-cf0c-4554-ab5f-bbb19b451914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Submit')]</value>
      <webElementGuid>3db42ed1-662c-4cb8-a4d9-e375dae71e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[3]/following::a[2]</value>
      <webElementGuid>5877d5b2-df51-4685-a9e7-ae64c7742245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[2]/following::a[2]</value>
      <webElementGuid>1d0cc802-a95d-4341-88a5-3392dcdbae5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[4]</value>
      <webElementGuid>df207fa6-6edd-4fe7-8d5c-0ea741804b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[4]</value>
      <webElementGuid>495f40a3-53c3-4b2b-a0c0-2bc1adc00461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>8d260b13-90b6-4b9d-8aaf-f84ed84454be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>339a4669-aa5a-4696-bf68-80db44b42a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>9decdae0-2662-4174-be04-1041b693b85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85' and @name = 'btn.submit' and @href = '#' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>3c68ff88-3abe-4825-9d61-0d791d2dcd8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
