<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you</name>
   <tag></tag>
   <elementGuidId>ea71b7d9-bb59-4dfe-b743-d92df0360d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupWin_f22520d4-e071-ec4a-7f1d-00a6c7e33803']/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.popup-header-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6d2c5ce-e735-4155-a33c-56a2935c4e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-header-text</value>
      <webElementGuid>be35c87a-1fc2-47db-85bd-9c4070b84b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you</value>
      <webElementGuid>1829d1b0-9f60-4723-9ef6-817bf40f52d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupWin_f22520d4-e071-ec4a-7f1d-00a6c7e33803&quot;)/div[@class=&quot;popup-header&quot;]/div[@class=&quot;popup-header-c&quot;]/div[@class=&quot;popup-header-wrapper&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;popup-header-text&quot;]</value>
      <webElementGuid>a6e394b0-9ac0-4025-8320-3e5c458e0ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contact Us Registered/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>41e237f1-77f9-4edf-8789-dbee9490804f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_f22520d4-e071-ec4a-7f1d-00a6c7e33803']/div/div[2]/div/div/div</value>
      <webElementGuid>ab50732f-44df-4594-8702-a32e949e6451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UserReplacementBet'])[1]/following::div[16]</value>
      <webElementGuid>d54c418c-5581-45c5-b3ba-38887825513e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST AK'])[1]/following::div[16]</value>
      <webElementGuid>55489b94-3b5f-4b27-b297-9d28768fbe0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[30]</value>
      <webElementGuid>616d2527-ebde-4f8b-a562-9f9491014eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you']/parent::*</value>
      <webElementGuid>b9bc3f85-7dfc-4311-9deb-1c1e53d791e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>1b92e74a-b954-4311-9ae6-d2f802f5b792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thank you' or . = 'Thank you')]</value>
      <webElementGuid>4aaa916c-4998-4a2b-8d33-ae7993d1a909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
