<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inquiry</name>
   <tag></tag>
   <elementGuidId>98bd5e57-248c-4c17-a989-5b3140bb604e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='8ae8ed46-3080-4c4c-9d3c-b44d4931a407_e046f48b-b185-4840-8095-4383736d3f48_radioButtonItem_0_base']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.input-control-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e50e22c2-f6eb-43e9-a3d6-1c2b2b6f7ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-control-text</value>
      <webElementGuid>ccba1943-968d-4803-9d40-2054dd61c350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inquiry</value>
      <webElementGuid>e79bc686-7222-4ad3-887f-fee6cd01a9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8ae8ed46-3080-4c4c-9d3c-b44d4931a407_e046f48b-b185-4840-8095-4383736d3f48_radioButtonItem_0_base&quot;)/span[@class=&quot;input-control-text&quot;]</value>
      <webElementGuid>949b5916-aa71-4b93-b6db-98c71c6034ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contact Us Registered/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>dc96479c-7640-4fde-9a54-4ab76689de29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='8ae8ed46-3080-4c4c-9d3c-b44d4931a407_e046f48b-b185-4840-8095-4383736d3f48_radioButtonItem_0_base']/span[2]</value>
      <webElementGuid>17a9f53b-777c-4c44-bac9-2fe321fd2198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='afterasteriks'])[4]/following::span[3]</value>
      <webElementGuid>eefe84a8-f3a5-4951-ae80-6aef969130bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Communication'])[1]/following::span[5]</value>
      <webElementGuid>6016cb66-a6c3-4669-83e5-00ea35882857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestion'])[1]/preceding::span[2]</value>
      <webElementGuid>e64ccee6-f98d-4ac8-a1cb-f3175a30e557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[1]/preceding::span[3]</value>
      <webElementGuid>99bc9982-cdf8-444a-a2a4-1d4ac42fd4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inquiry']/parent::*</value>
      <webElementGuid>8f3813dd-7fef-4119-a27e-8235a752cf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span[2]</value>
      <webElementGuid>a55019da-d7f1-4e38-94a0-3ac4f87f9be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Inquiry' or . = 'Inquiry')]</value>
      <webElementGuid>1659217b-ac17-4633-9828-0aefd7697e66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
