<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_afterasteriks_Cell Cell668</name>
   <tag></tag>
   <elementGuidId>af2b9d20-67e4-45dd-8c52-68a65065424e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='78e44ab4-24ec-1500-3de2-ce79ce5fec87']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#78e44ab4-24ec-1500-3de2-ce79ce5fec87</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>957e53fe-138a-4138-9bcf-39a579060ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>78e44ab4-24ec-1500-3de2-ce79ce5fec87</value>
      <webElementGuid>c0002210-6bb5-4235-9c2b-d5a644cca6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layouttype</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>f0b617e9-ce1b-45ef-9d75-ce3343af1f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8b2cd7a2-4f7f-4313-a1ea-841e43f6689a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-cell droptarget lastcellinrow</value>
      <webElementGuid>2f4b0f94-15ec-4dca-9d00-a67334485ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e4cf7176-0534-4367-b100-dbe0c1508411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cell Cell668</value>
      <webElementGuid>87bdd4a2-773d-47bb-85a5-ec9705ef6f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controltype</name>
      <type>Main</type>
      <value>Cell</value>
      <webElementGuid>1fef9733-761c-4737-b060-56a338fa5b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4ed75191-be7a-4fdb-9576-8ca99226b569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f1267568-2145-4296-bd06-53dce0bf7c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;78e44ab4-24ec-1500-3de2-ce79ce5fec87&quot;)</value>
      <webElementGuid>e84fcd36-de7b-48e6-952f-ca6fe5874e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contact Us Registered/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>47a79bd2-5b34-4811-9d44-3a64f5db808c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='78e44ab4-24ec-1500-3de2-ce79ce5fec87']</value>
      <webElementGuid>7628db34-71ce-412e-8b0c-65c3b1f9e437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8ae8ed46-3080-4c4c-9d3c-b44d4931a407_ec46e5ca-21b1-edd5-161c-fd91059d39f6_Table']/span[16]</value>
      <webElementGuid>0305551e-53fd-40a8-8bfa-ad55072c17c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='afterasteriks'])[7]/following::span[1]</value>
      <webElementGuid>666d0541-8045-49a0-a2de-235bbc7336b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acknowledgment'])[1]/following::span[3]</value>
      <webElementGuid>0fd9d4ae-e473-4b54-9963-a7e95f9ca437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/preceding::span[5]</value>
      <webElementGuid>5796f667-1802-427e-a280-a7d7b39cacef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[1]/preceding::span[7]</value>
      <webElementGuid>91765e29-1747-4122-aa23-76799a71bbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[16]</value>
      <webElementGuid>d36a5f23-7f1d-4548-a7de-b209bc03a19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '78e44ab4-24ec-1500-3de2-ce79ce5fec87' and @name = 'Cell Cell668']</value>
      <webElementGuid>0117e06a-3075-4db7-87cf-887cdc2a3e31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
