<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Suggestion</name>
   <tag></tag>
   <elementGuidId>ceea0c64-7c14-4053-9e8e-fbb2fed5e9bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='8ae8ed46-3080-4c4c-9d3c-b44d4931a407_e046f48b-b185-4840-8095-4383736d3f48_radioButtonItem_1_base']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8ae8ed46-3080-4c4c-9d3c-b44d4931a407_e046f48b-b185-4840-8095-4383736d3f48_radioButtonItem_1_base > span.input-control-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8b7ccf0-bd0b-4784-84d1-1740947e7771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-control-text</value>
      <webElementGuid>09c80b46-dda5-48c3-9a53-14d52b4618f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suggestion</value>
      <webElementGuid>0df083ed-8c73-424d-a0a0-19d722926653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8ae8ed46-3080-4c4c-9d3c-b44d4931a407_e046f48b-b185-4840-8095-4383736d3f48_radioButtonItem_1_base&quot;)/span[@class=&quot;input-control-text&quot;]</value>
      <webElementGuid>964722c4-6076-44d4-902e-d9fe0a26a795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contact Us Registered/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>8486a930-a9e3-4eb9-a2e5-f2a64cf2219d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='8ae8ed46-3080-4c4c-9d3c-b44d4931a407_e046f48b-b185-4840-8095-4383736d3f48_radioButtonItem_1_base']/span[2]</value>
      <webElementGuid>beab33ba-59ff-48be-8760-1d9f18af226c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inquiry'])[1]/following::span[2]</value>
      <webElementGuid>3ffc4347-739f-4f19-b32e-d6173ef3e9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='afterasteriks'])[4]/following::span[5]</value>
      <webElementGuid>fef8b0f3-4c5b-49f0-a90d-5257ae068031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[1]/preceding::span[1]</value>
      <webElementGuid>e56066cd-a3b6-4e34-8166-e5fc5e39aa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual'])[1]/preceding::span[2]</value>
      <webElementGuid>18408be0-f98d-49ba-8c6e-aa053e345662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suggestion']/parent::*</value>
      <webElementGuid>93b3077d-16fd-459d-a24f-357bcb7d5839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span[2]</value>
      <webElementGuid>4da074cf-ca84-4b8a-b272-c14634ff594e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Suggestion' or . = 'Suggestion')]</value>
      <webElementGuid>78f6cfc3-d3f0-4866-ab68-02097be40b31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
