<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit</name>
   <tag></tag>
   <elementGuidId>114697cb-8326-412f-b163-686eabed464a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='2089659d-02cc-4ea6-8f6e-71308f07be24_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2089659d-02cc-4ea6-8f6e-71308f07be24_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1084f8a-89d7-4359-8769-7b159d55fcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2089659d-02cc-4ea6-8f6e-71308f07be24_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      <webElementGuid>9f5a2e68-d124-4414-89f6-3949fc261bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.submit</value>
      <webElementGuid>a1db8bd7-7ecb-4c59-be83-bcc2abe0fba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button visible</value>
      <webElementGuid>7cd7c24f-1bcf-4510-a298-5c44982f0b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>98637ea4-5762-4308-b5b5-c714868a5985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>15399c60-0025-47b7-aa54-0f733edcb65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isvisible&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;\u003e\u003cMargin\u003e\u003cDefault\u003e3px\u003c/Default\u003e\u003c/Margin\u003e\u003c/Style\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>6f2d71a5-aa05-4c4a-a571-02eb70864562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>c7e6eeca-4e51-42e5-b4c3-67eb5a663e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2089659d-02cc-4ea6-8f6e-71308f07be24_286725f8-ee17-3bc5-6142-b060c4031e85&quot;)</value>
      <webElementGuid>6b814d56-57b3-400d-90bf-7176fd7ebec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Contact Us Anonymous User/Page_- Contact Us/iframe_Contact Us_K2smartformFrame</value>
      <webElementGuid>f5c4273a-686a-4c9b-bf14-7d582a9f60bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='2089659d-02cc-4ea6-8f6e-71308f07be24_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      <webElementGuid>7c823754-fffb-4e11-8634-5c4d9a419fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='1efff9ff-d3c3-61aa-b430-98ff6200bd23']/a</value>
      <webElementGuid>1c6b7352-6fa2-4e86-b43c-036e52040e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Submit')]</value>
      <webElementGuid>25f65f8f-a134-4c2c-a2ed-f180914bb96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ActingAsTypeID_Business'])[1]/following::a[2]</value>
      <webElementGuid>15293fac-6d4b-4a16-b0a3-ce65148b26f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ActingAsTypeID_Individual'])[1]/following::a[2]</value>
      <webElementGuid>991e0a6d-4530-4214-b34d-708a57f32f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[4]</value>
      <webElementGuid>83ea84bd-d4e3-4307-a7eb-3e9f7089bc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[4]</value>
      <webElementGuid>7c42124d-b06f-4b9c-9d2c-945c682d5e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>b4566a00-13b7-407f-beba-b826fad060ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>b79a744b-9746-419e-83cc-e17473dfffd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>63f8a14f-a9f4-4cac-8015-b70db749d5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '2089659d-02cc-4ea6-8f6e-71308f07be24_286725f8-ee17-3bc5-6142-b060c4031e85' and @name = 'btn.submit' and @href = '#' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>9b78e6e6-a646-4c90-8894-64fc63a8f475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
