<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Contact Us_K2smartformFrame</name>
   <tag></tag>
   <elementGuidId>fcb73de9-c57f-41e8-9cab-efb0bda9d0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='K2smartformFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K2smartformFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fcacdcd9-5aaf-421d-a893-a7fa9a621b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K2smartformFrame</value>
      <webElementGuid>88beeaef-6f64-49e6-8c83-f5a60dc6d9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/ONL.ContactUs.External.Navigation?Token=pMlf6dLnbTQqr05w8OaUSWKWw9IbN05Rw+ytjfgTdk0l3MtppQ8WTeT+ibNMo7MtyRSP1F9kb9BoqzSLZ4c5pibw5ouXAZqW4Md7mALXISWCzi7FT0+ET8OQH7B7hEgufmegtzzNDCOA0PEQRPKXionGXYEJaJi1CCxDLHugrIt4NPeqdMQRT0nsbZybYJJywABiEVFjKFoCgc+38P0bh4rRs2ki6obwSbsts4BaMw7fgLxNsyr2RXmnJAXOJZvZIoM6nucLrHoS8eLHQBaWUsZgsOWzbe0OqIZuPXU3RmcbMgSv37oOlOn0rlMGz1W2RgcjpjxRTsgcFR5kWhdnUhwwr4pY8PequtxzwCzQyNeYVVSW9wWvxWQvLXClBQEnu8pb/Yln1WQrQ7kmfMYoVJgZlRssRN+u</value>
      <webElementGuid>d68f8099-96c6-4e63-8322-8c14c7c715d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ONL.ContactUs.External.Navigation</value>
      <webElementGuid>ce3e5b3c-04f0-48a4-a499-7fb0bd61ddd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>K2smartformFrame</value>
      <webElementGuid>0c2b51b6-567c-4942-8179-d19a968cb9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>57cf042f-e76d-4160-b32d-027694271b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bf5b02ca-2d74-42d0-9f5c-57bd9a0c7884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89d41153-0572-4cfb-a527-ce29318ce71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b0fb1c1d-294e-44d4-a77e-de2c0fb41a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e185c402-ebf0-4d64-a755-40be783e853b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f493cc4-d1a0-4f8f-b703-bd1ce175105a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e98efc8d-65d6-48da-b3c1-78373fbb408c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K2smartformFrame&quot;)</value>
      <webElementGuid>a306a165-8748-41c8-b8eb-e99e41ee13b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='K2smartformFrame']</value>
      <webElementGuid>d9d283ad-c02c-404e-b3d1-a41e44d46f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl42_g_df36dbf5_1f2c_49bb_a16b_a41cf4ff7c69_ctl00_pnlBody']/iframe</value>
      <webElementGuid>ab4bd142-db65-4590-bc2e-de2165ce4200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>09a592e1-f7ec-4b68-abc1-57ccd4d194fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'K2smartformFrame' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/ONL.ContactUs.External.Navigation?Token=pMlf6dLnbTQqr05w8OaUSWKWw9IbN05Rw+ytjfgTdk0l3MtppQ8WTeT+ibNMo7MtyRSP1F9kb9BoqzSLZ4c5pibw5ouXAZqW4Md7mALXISWCzi7FT0+ET8OQH7B7hEgufmegtzzNDCOA0PEQRPKXionGXYEJaJi1CCxDLHugrIt4NPeqdMQRT0nsbZybYJJywABiEVFjKFoCgc+38P0bh4rRs2ki6obwSbsts4BaMw7fgLxNsyr2RXmnJAXOJZvZIoM6nucLrHoS8eLHQBaWUsZgsOWzbe0OqIZuPXU3RmcbMgSv37oOlOn0rlMGz1W2RgcjpjxRTsgcFR5kWhdnUhwwr4pY8PequtxzwCzQyNeYVVSW9wWvxWQvLXClBQEnu8pb/Yln1WQrQ7kmfMYoVJgZlRssRN+u' and @title = 'ONL.ContactUs.External.Navigation']</value>
      <webElementGuid>cb36e7c5-e546-44e1-92fb-e658f8a2dd0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
