<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>2df35be3-431e-4b1c-b480-0d3983934a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupWin_b5379069-2e2d-e099-6e23-ec1161660e98']/div/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.top-calendar-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08940dde-4613-404b-81ff-9876b0b75b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-calendar-right</value>
      <webElementGuid>a7e00a83-3aca-48d1-8c6a-bd4e060799fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6e140dac-810f-4ac5-b6c1-1f1e155d2d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>a24ed8ed-9719-4854-9d5b-709533f3e75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupWin_b5379069-2e2d-e099-6e23-ec1161660e98&quot;)/div[@class=&quot;calendar-outline&quot;]/div[@class=&quot;top-calendar&quot;]/a[@class=&quot;top-calendar-right&quot;]</value>
      <webElementGuid>bf968f11-9ef3-4429-94cb-7f1925e5a31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1</value>
      <webElementGuid>48a022b5-439b-4413-8d33-79501e0b0852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_b5379069-2e2d-e099-6e23-ec1161660e98']/div/div/a[3]</value>
      <webElementGuid>6b818403-2fda-461c-973c-949fe03b4e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun 2023'])[1]/following::a[1]</value>
      <webElementGuid>4c9b25c5-0cd5-4053-bdd1-555564801efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pafos/Πάφου'])[1]/following::a[4]</value>
      <webElementGuid>db51a5ee-d637-4aad-97c7-e34966d0e1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::a[1]</value>
      <webElementGuid>9d6ce9d3-1647-4d74-8800-c43638212317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tu'])[1]/preceding::a[1]</value>
      <webElementGuid>47f6c3e0-d2e9-4f6c-a221-cef0f0c28bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>42227a98-885f-4eb8-89b4-7797f7aafd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a[3]</value>
      <webElementGuid>86d710a8-96e7-48f6-8f10-41c30f8645ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>f9300554-b73c-459e-9803-8a7aaa2fce9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
