<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_01</name>
   <tag></tag>
   <elementGuidId>2674c200-9236-432f-8d5a-cf4af8448dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupWin_6e0b9edc-79a8-52a3-9448-42f193dc45a4']/div/div[2]/div/div[2]/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.day.xy_3_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1cf6c818-02dd-4317-af3d-7fdaeb10a326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>2d314ff3-fa48-41e8-8a44-8c74b6f925d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>calendardate</name>
      <type>Main</type>
      <value>2023-06-01</value>
      <webElementGuid>f687ec07-f514-41df-9132-87884a3094d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day xy_3_0</value>
      <webElementGuid>8bf878f4-9182-4cad-9608-8700017b4a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01</value>
      <webElementGuid>52d51a64-6ae5-43ce-859a-6726e24b5c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupWin_6e0b9edc-79a8-52a3-9448-42f193dc45a4&quot;)/div[@class=&quot;calendar-outline&quot;]/div[@class=&quot;calendar-content-outside&quot;]/div[@class=&quot;calendar-content&quot;]/div[@class=&quot;calendar-row week&quot;]/a[@class=&quot;day xy_3_0&quot;]</value>
      <webElementGuid>eddf3728-d11c-4f19-9f6a-cc4c7d35f8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1</value>
      <webElementGuid>d2dd6b3e-568d-4d8f-9e92-34296508bfa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_6e0b9edc-79a8-52a3-9448-42f193dc45a4']/div/div[2]/div/div[2]/a[4]</value>
      <webElementGuid>8357793f-450b-447b-bb83-a955f7f7bb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'01')]</value>
      <webElementGuid>754a90c2-23c9-4b02-a6bb-530415c59067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::a[4]</value>
      <webElementGuid>2dfe3b18-f841-45b3-80c4-49ddc5b8731a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[4]</value>
      <webElementGuid>21e674b6-5301-48c8-9e65-cb981f1152e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected day:'])[1]/preceding::a[39]</value>
      <webElementGuid>436db5ca-89ba-4e85-84a7-ddc20420184b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, 29 June 2023'])[1]/preceding::a[39]</value>
      <webElementGuid>b6c49d19-7b16-43e4-a424-8164c6c74d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01']/parent::*</value>
      <webElementGuid>ce1b1ad7-38ce-4eee-8fd0-b17e2d5d58b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[7]</value>
      <webElementGuid>d6fcdb3e-9123-45cf-a65a-263d5cdd3f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[4]</value>
      <webElementGuid>5e014131-ae5b-4604-bb68-aadfbca4e66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '01' or . = '01')]</value>
      <webElementGuid>dac1fa3e-60b1-4167-8856-94c58161a01a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
