<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_12</name>
   <tag></tag>
   <elementGuidId>a07df448-a2e6-4677-9b5e-6165d98f7640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupWin_fde0a5e7-f308-30a1-d1ac-b6224d2b787a']/div/div[2]/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.day.xy_0_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3858260c-ff01-401d-80c0-c23a3a121324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>80b1fcca-e39b-4e8c-9052-4e8349fd128b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>calendardate</name>
      <type>Main</type>
      <value>2023-06-12</value>
      <webElementGuid>9ad2a851-c9db-40f6-b5cf-69ef7a4122bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day xy_0_2</value>
      <webElementGuid>6b779593-9715-4a98-8a90-f30e827ef215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>0a3e9963-01bb-41a2-b73f-c804cc0c2039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupWin_fde0a5e7-f308-30a1-d1ac-b6224d2b787a&quot;)/div[@class=&quot;calendar-outline&quot;]/div[@class=&quot;calendar-content-outside&quot;]/div[@class=&quot;calendar-content&quot;]/div[@class=&quot;calendar-row week&quot;]/a[@class=&quot;day xy_0_2&quot;]</value>
      <webElementGuid>deb39068-53e6-40fb-a9e6-48160d95fa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2_3</value>
      <webElementGuid>cfeb2c5e-139c-425f-902c-7b3ce344055f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_fde0a5e7-f308-30a1-d1ac-b6224d2b787a']/div/div[2]/div/div[4]/a</value>
      <webElementGuid>be8ed023-dfc1-4453-a4af-ccf991303e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'12')]</value>
      <webElementGuid>3e9a0777-95ad-4c8d-a6bb-68096f3d9223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::a[15]</value>
      <webElementGuid>1c428e9a-7c0b-4413-bb36-6d6016d937ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[15]</value>
      <webElementGuid>ef574d53-1c2c-40c7-a56c-285a05b4ad79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected day:'])[1]/preceding::a[28]</value>
      <webElementGuid>b0df76a6-9be8-43dc-92da-3734b4d19c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, 29 June 2023'])[1]/preceding::a[28]</value>
      <webElementGuid>4acaf31b-1729-427b-a5be-8f1485408d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12']/parent::*</value>
      <webElementGuid>8c88e282-9c87-4629-8ddd-3b363e58c200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[18]</value>
      <webElementGuid>e7abbfa4-3ff8-44a6-8722-522d0fd58684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>2bbfb1bc-61eb-47d9-8968-a70fc7663491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '12' or . = '12')]</value>
      <webElementGuid>6d3d49b7-b8f6-4ca6-b4a4-a2fad0584bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
