<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_29</name>
   <tag></tag>
   <elementGuidId>f4f031bd-3cc6-4949-951e-35bee5321843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupWin_94b0744d-d4c9-bed7-85f3-85baa20a5c2e']/div/div[2]/div/div[6]/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.day.xy_3_4.selected.today.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fb0602e-32ef-4cea-9856-d7fe66e39ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>38a6d815-b416-4bbe-8c8d-bd5fce23aa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>calendardate</name>
      <type>Main</type>
      <value>2023-06-29</value>
      <webElementGuid>caa0f5ec-a6a7-4acb-94c1-f27433b205f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day xy_3_4 selected today active</value>
      <webElementGuid>2193c122-a5c7-44a0-b307-159e58bc6bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>0f09b3cc-9a0f-47b9-93bf-be95d9798b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupWin_94b0744d-d4c9-bed7-85f3-85baa20a5c2e&quot;)/div[@class=&quot;calendar-outline&quot;]/div[@class=&quot;calendar-content-outside&quot;]/div[@class=&quot;calendar-content&quot;]/div[@class=&quot;calendar-row week&quot;]/a[@class=&quot;day xy_3_4 selected today active&quot;]</value>
      <webElementGuid>67ed3605-fdbf-43b1-965e-ab432c0c7a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2_3_4</value>
      <webElementGuid>1768dde2-f18d-49b5-9f37-5e1024394a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_94b0744d-d4c9-bed7-85f3-85baa20a5c2e']/div/div[2]/div/div[6]/a[4]</value>
      <webElementGuid>af1a1beb-0dfa-4c1f-a917-d32605cd6068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'29')])[2]</value>
      <webElementGuid>96715766-5c44-4b38-9214-981668ed0523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::a[32]</value>
      <webElementGuid>76e35807-ef3d-46a1-a77e-dadbad8349f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[32]</value>
      <webElementGuid>1647555d-85b6-4052-91d9-9cd3b7361bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected day:'])[1]/preceding::a[11]</value>
      <webElementGuid>45401ff2-2ead-4e0f-a51e-edb6f4fc8f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, 29 June 2023'])[1]/preceding::a[11]</value>
      <webElementGuid>5c05f13a-cce9-4610-bb29-ed35406f5342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[49]</value>
      <webElementGuid>215832c7-7dc6-4aa4-b9bf-4cd7db055b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a[4]</value>
      <webElementGuid>418350ae-cddf-424d-bbd9-2497b5371d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '29' or . = '29')]</value>
      <webElementGuid>10d7c19e-bb8c-4e50-8635-008a9bd02f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
