<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_31</name>
   <tag></tag>
   <elementGuidId>5abb967f-fc56-4061-9a97-33b4c6939520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupWin_b5379069-2e2d-e099-6e23-ec1161660e98']/div/div[2]/div/div[6]/a[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.day.xy_6_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>276e2bec-9385-409e-a0ec-2b5572031bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>ed50c758-37da-4d59-9ce7-5a3b2371ae79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>calendardate</name>
      <type>Main</type>
      <value>2023-12-31</value>
      <webElementGuid>31d3a854-79c8-497f-9db5-540686b6531c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day xy_6_4</value>
      <webElementGuid>c761022a-27ee-4caa-97bc-7591726fcd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>bf67033c-d05a-4385-8cd7-3890136960a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupWin_b5379069-2e2d-e099-6e23-ec1161660e98&quot;)/div[@class=&quot;calendar-outline&quot;]/div[@class=&quot;calendar-content-outside&quot;]/div[@class=&quot;calendar-content&quot;]/div[@class=&quot;calendar-row week&quot;]/a[@class=&quot;day xy_6_4&quot;]</value>
      <webElementGuid>bcc647a6-ca50-4744-b9da-afe13b59c43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1</value>
      <webElementGuid>99e58a2c-fefc-4417-9838-ee103eb1176f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_b5379069-2e2d-e099-6e23-ec1161660e98']/div/div[2]/div/div[6]/a[7]</value>
      <webElementGuid>6d44e175-f53e-4680-940b-73b40064ff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'31')]</value>
      <webElementGuid>f1e96824-71f3-4426-9119-df490cc1f535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::a[35]</value>
      <webElementGuid>21805da1-433f-449a-8ac8-b690dadd76bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[35]</value>
      <webElementGuid>496d0144-6b2d-46fd-9ded-5c0c56bc1088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected day:'])[1]/preceding::a[8]</value>
      <webElementGuid>22d6ef59-970c-4263-9273-f64ff07a1126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, 29 June 2023'])[1]/preceding::a[8]</value>
      <webElementGuid>a3a7f276-e97b-4a6e-a3af-85f3d77bbdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>9d0c59d8-17aa-4c6d-a531-096e8c0197de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[38]</value>
      <webElementGuid>16e1b2bf-95b5-4768-8b0d-658f5e0e54e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a[7]</value>
      <webElementGuid>f75f8e0f-e477-44d2-9218-09566da9c3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '31' or . = '31')]</value>
      <webElementGuid>c63e044c-a6ca-4cfc-b756-4692cc8f0db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
