<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OK_1 (1)</name>
   <tag></tag>
   <elementGuidId>03df91fd-9c9d-4a66-baa2-683f56af4ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='messageBoxButton_OK1688019939641']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#messageBoxButton_OK1688019939641</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06e4a5a4-0688-4c40-9986-066b4b9370f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messageBoxButton_OK1688019939641</value>
      <webElementGuid>5fc6b2e3-e831-45e4-ae59-6b01da8b46ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button button</value>
      <webElementGuid>2db36125-8441-4079-8606-8ca19711e90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>037b2a04-8086-4bd6-91ca-7f91e57c932d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>b2d58639-bb7b-47f6-8265-6280938acf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageBoxButton_OK1688019939641&quot;)</value>
      <webElementGuid>57e113c0-6651-4cd8-8599-d3364f7dadf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2</value>
      <webElementGuid>cc47ceea-5ce5-4d9c-82c9-f5bffbd85656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='messageBoxButton_OK1688019939641']</value>
      <webElementGuid>dcf03575-2b9f-4757-94e6-24a15ab5d04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupWin_1f7245d8-73cd-173f-a8aa-dbb7be7993b9']/div[3]/div[2]/a</value>
      <webElementGuid>025f15f8-f893-4db5-8a53-79319aa1fe90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'OK')]</value>
      <webElementGuid>5973c1dc-8d4b-40d1-994a-780aa891e87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The changes in the current section have been saved in application: DRF-31842'])[1]/following::a[1]</value>
      <webElementGuid>0ed3268d-69bd-47ca-964e-398a3475b72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[2]/following::a[2]</value>
      <webElementGuid>7bb77674-babd-421e-99b5-877f70a075c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>e0ccd577-6330-44f8-a02d-caab9401268f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[391]</value>
      <webElementGuid>e6e9bdf1-388e-4ba2-bd1d-627eaa5583ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>ba6eee93-0c6e-4ad3-a778-932c0c26b298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'messageBoxButton_OK1688019939641' and @href = 'javascript:' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>f0c890c6-fa9c-4045-8297-eafdcb68d6f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
