<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save (4)</name>
   <tag></tag>
   <elementGuidId>a3988bd4-06ea-4a85-81b3-fe75cd42741c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='e6073a6a-e4d8-98ef-553c-b8cbc96c7688_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e6073a6a-e4d8-98ef-553c-b8cbc96c7688_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1de5c18e-d80c-4afe-a7fe-eed39d92b69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e6073a6a-e4d8-98ef-553c-b8cbc96c7688_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      <webElementGuid>8b80226e-2168-4210-b472-392789e915f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.save</value>
      <webElementGuid>e7637329-dca8-47fb-8a61-531edd171ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button enabled</value>
      <webElementGuid>d00b04a1-f780-4d0a-ae11-452f9e350457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>65df6c0d-f8aa-4488-a8cb-9e0e7e946be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a9c8cf1-2b6a-40f4-899d-abe15d6df104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isenabled&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;/\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>b96f0f9a-0f2b-46b4-83e4-96a95cb1d261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a10fdf29-38bb-4ebe-9200-4f0470a683bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>14ca78e1-febd-4851-90aa-cacd60892733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e6073a6a-e4d8-98ef-553c-b8cbc96c7688_27984355-7420-4f86-bf52-e44cb8ce6c2a&quot;)</value>
      <webElementGuid>d9ece606-638d-4515-ab19-1b01659e6651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2_3_4_5</value>
      <webElementGuid>236c329a-6ca1-42bd-986d-363a5903736e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='e6073a6a-e4d8-98ef-553c-b8cbc96c7688_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      <webElementGuid>7d25345e-5b59-4d81-85fb-27bebb7cdc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='b471273a-9b0a-4cc8-86d9-c390af816a0d']/a</value>
      <webElementGuid>75a35bfc-befd-4961-8903-3eeba82e5ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>c6737a00-074a-4809-987a-dd463c33b881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::a[1]</value>
      <webElementGuid>cf0d2c4b-c8ba-473f-b89b-bff231c62879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[5]</value>
      <webElementGuid>1a260565-3367-46fc-b781-02e716e78a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[5]</value>
      <webElementGuid>23f92b39-134a-4546-9f4e-be9a94373d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>730ed869-8ff0-4d67-9a01-e205edb9910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>3207ea1d-117e-42ed-9e12-a230a52b3508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div[2]/div/div/div/span/a</value>
      <webElementGuid>ce63d720-2ccb-4fdb-a170-14c60f8dd87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'e6073a6a-e4d8-98ef-553c-b8cbc96c7688_27984355-7420-4f86-bf52-e44cb8ce6c2a' and @name = 'btn.save' and @href = '#' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>c4e4e421-233c-4e4a-b08c-bbfba4c624c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
