<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save (2)</name>
   <tag></tag>
   <elementGuidId>18636ac4-b4c0-4861-80f1-3f62ba517ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='4d9d21df-61b3-4a01-980e-5a48159e65fd_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4d9d21df-61b3-4a01-980e-5a48159e65fd_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f07a54e-aacb-46c8-9d8c-87bccdbd3452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4d9d21df-61b3-4a01-980e-5a48159e65fd_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      <webElementGuid>a0391956-9588-45df-8d7e-d2c995514f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.save</value>
      <webElementGuid>d2618168-88e0-4fec-a2eb-3a6678130ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button enabled</value>
      <webElementGuid>503ccaf4-0fbb-452c-88d6-76a31566e42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7241773e-ab5b-4436-ad44-70396067db13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bdf8d9d5-f54f-4aee-aab5-8984c88d9090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isenabled&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;/\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>e1059b22-c505-4ae9-b8f8-f3226c610fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a1805a1-93cf-4abe-97d8-6f560eca9ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>5dc2b7ea-2515-411a-980a-505071c9f256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4d9d21df-61b3-4a01-980e-5a48159e65fd_27984355-7420-4f86-bf52-e44cb8ce6c2a&quot;)</value>
      <webElementGuid>18c8d51b-c11f-4224-a464-1de4b2c75e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2</value>
      <webElementGuid>1905cbf6-079d-4628-a675-41742da3d78c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='4d9d21df-61b3-4a01-980e-5a48159e65fd_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      <webElementGuid>e3482ce3-738f-4f53-ae98-34c0dac52df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='b471273a-9b0a-4cc8-86d9-c390af816a0d']/a</value>
      <webElementGuid>b6b86874-8c29-42d7-875e-6883198152fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>366de8d0-7976-4768-a28b-f0d5199faaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[11]/following::a[1]</value>
      <webElementGuid>2ca3ede4-71e7-4c6e-9911-1affd9269ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date'])[1]/following::a[2]</value>
      <webElementGuid>7b325673-82db-4dab-99df-a0e776710408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[5]</value>
      <webElementGuid>1e8e5ff5-3dba-4267-a578-b25e171cae9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[5]</value>
      <webElementGuid>f786e51b-6ff4-4d34-b014-3b3bdeb81967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>53fecfdc-41f0-4ee9-99ff-f44da669d26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div[2]/div/div/div/span/a</value>
      <webElementGuid>7b64ee22-cf7a-4e30-b3b4-d240c5043173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '4d9d21df-61b3-4a01-980e-5a48159e65fd_27984355-7420-4f86-bf52-e44cb8ce6c2a' and @name = 'btn.save' and @href = '#' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>799dffca-b14c-459c-bfd0-1f51b41705db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
