<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save (1)</name>
   <tag></tag>
   <elementGuidId>fcf7371f-fa9f-4dbd-aada-73f13bcba048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='26de5e8d-6e6d-4936-9599-caacb2c2b9c0_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#26de5e8d-6e6d-4936-9599-caacb2c2b9c0_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c96f09d-c721-46f6-ab5f-6d6a78b91bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>26de5e8d-6e6d-4936-9599-caacb2c2b9c0_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      <webElementGuid>54faa4e9-0b4c-40be-bc21-708d2f6da84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.save</value>
      <webElementGuid>cd228d73-f4ee-4bec-afbc-b9b0288130fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button enabled</value>
      <webElementGuid>bb590bfc-aa2c-41df-a36c-290ea8285600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ee01190a-7e61-4623-ae85-58ec53747824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37ec04b0-8ba7-4446-967d-29534c5c016f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isenabled&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;/\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>ff492da2-ad35-471c-9123-b2f5c0198f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d04fc18-5830-4c28-805f-40d7f18c2094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>8a658600-058a-4701-8994-dba82f8a0ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;26de5e8d-6e6d-4936-9599-caacb2c2b9c0_27984355-7420-4f86-bf52-e44cb8ce6c2a&quot;)</value>
      <webElementGuid>8dc04908-a5fd-40e5-8169-db4bc0d4c54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1</value>
      <webElementGuid>53969ddd-a6ab-461c-9dcf-3a7b137ecc58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='26de5e8d-6e6d-4936-9599-caacb2c2b9c0_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      <webElementGuid>b4e71443-f8bb-4f29-bb41-06fb4f9df552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='b471273a-9b0a-4cc8-86d9-c390af816a0d']/a</value>
      <webElementGuid>42b481e5-0e21-4972-8f1f-85a6ed7807a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>13f8fc57-fc0b-4d6c-92ca-1688b0c44308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[11]/following::a[1]</value>
      <webElementGuid>f22fd9a4-2eba-466c-ba24-55b35c911857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date'])[1]/following::a[2]</value>
      <webElementGuid>926893ba-1108-4e60-b6bb-b10e0d039f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[5]</value>
      <webElementGuid>cd324a6e-530e-4179-ae4f-40e7fffb31d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[5]</value>
      <webElementGuid>435669d7-36d7-4325-a535-22e2e7427942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>5e576c93-45c4-4690-ba8c-cf6e8fa6ea93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div[2]/div/div/div/span/a</value>
      <webElementGuid>d4704783-c3d9-4e8a-bd44-71b47f539be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '26de5e8d-6e6d-4936-9599-caacb2c2b9c0_27984355-7420-4f86-bf52-e44cb8ce6c2a' and @name = 'btn.save' and @href = '#' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>93d0a2c6-4f9a-405c-956d-fa087ae63049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
