<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>62ef8920-2090-4b63-bcd6-534395659282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='eadb28c9-4462-471d-b93c-fb0e2b8831ed_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eadb28c9-4462-471d-b93c-fb0e2b8831ed_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f822a40-3263-4e3e-b115-9fd22ce952f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eadb28c9-4462-471d-b93c-fb0e2b8831ed_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      <webElementGuid>b4723b4b-b6bd-4642-873f-efbb38fcb1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.save</value>
      <webElementGuid>6fa3323c-6005-4f33-bc1d-d5f8f0997639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button enabled</value>
      <webElementGuid>4cfcbcbf-c3de-474d-b7da-de4b323f40f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0bd94f0c-1a5a-4373-892b-eb4297995b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb04dae6-8fbd-43f1-8001-52ce3fbec18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isenabled&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;/\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>93c37e10-0dcb-4fb9-9bce-e2c15a26c7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2244976b-4d13-4e58-b259-33ef70e5f235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>3541dc4f-7212-4954-9145-ee2c9b94fcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eadb28c9-4462-471d-b93c-fb0e2b8831ed_27984355-7420-4f86-bf52-e44cb8ce6c2a&quot;)</value>
      <webElementGuid>80c3ab6e-9294-4a67-a638-614475ee4356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content</value>
      <webElementGuid>9eec5e8f-02b9-4537-9de9-e48bf461f800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='eadb28c9-4462-471d-b93c-fb0e2b8831ed_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      <webElementGuid>e6caede5-7056-4eea-9e88-8054e64cec45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='b471273a-9b0a-4cc8-86d9-c390af816a0d']/a</value>
      <webElementGuid>ec8bfef1-c6e2-4d15-8f58-4cace98934cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>52376e33-53d5-4260-87d8-a7471339c5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorized Representative Company Registration Number'])[1]/following::a[1]</value>
      <webElementGuid>27c7ab7f-7d4c-4dee-b8eb-78ca660a82f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorized Representative License Number'])[1]/following::a[1]</value>
      <webElementGuid>c133f6ed-8262-4a43-b99c-ed09a2b89b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[6]</value>
      <webElementGuid>9dcae8d8-7cbe-4fb3-96b9-f8e0864e6121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[6]</value>
      <webElementGuid>57d0d6e1-d2c4-45c3-8dad-66ddbf9325cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>0806caa6-5482-4fa5-bf62-03e34a66aaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>68ea0aca-4f6f-41c1-8502-a3dddfdce8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div[2]/div/div/div/span/a</value>
      <webElementGuid>db9d8196-f7e9-4999-b689-dfb43daf7230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'eadb28c9-4462-471d-b93c-fb0e2b8831ed_27984355-7420-4f86-bf52-e44cb8ce6c2a' and @name = 'btn.save' and @href = '#' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>beecfbf7-011e-4f67-bfa5-a2ba9a535b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
