<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save (3)</name>
   <tag></tag>
   <elementGuidId>92c234b0-c62f-410d-a0ea-e4df30aea52a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='e9a15c51-ff54-41cd-be89-a295cf3324df_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e9a15c51-ff54-41cd-be89-a295cf3324df_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c502b5f3-4afe-4706-a6df-deb6753cdeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e9a15c51-ff54-41cd-be89-a295cf3324df_27984355-7420-4f86-bf52-e44cb8ce6c2a</value>
      <webElementGuid>23ce0833-a0e0-4b06-9c81-dbded3bad642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.save</value>
      <webElementGuid>616292b4-2ad6-4a1b-ae0a-bab469aca8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button enabled</value>
      <webElementGuid>d1ed27df-361c-4e01-97f3-cf188d97aad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2ed4692e-da13-4c31-80f7-797ff93c5716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d31ef540-9c5c-43c0-b646-cc24eb81207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isenabled&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;/\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>97d67085-de26-4910-8ac1-ce6bedac6988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab87308c-6903-4c67-936c-85c697e61ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>e8c48819-2f9c-41c7-8b56-a691e2d887b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e9a15c51-ff54-41cd-be89-a295cf3324df_27984355-7420-4f86-bf52-e44cb8ce6c2a&quot;)</value>
      <webElementGuid>385a5bbd-fa24-4e95-8c48-b1bc6c5e95bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2_3_4</value>
      <webElementGuid>9deee84d-4f3f-4996-b45e-391d1ed92118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='e9a15c51-ff54-41cd-be89-a295cf3324df_27984355-7420-4f86-bf52-e44cb8ce6c2a']</value>
      <webElementGuid>7d350489-95da-40e2-997b-55ef9761bb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='b471273a-9b0a-4cc8-86d9-c390af816a0d']/a</value>
      <webElementGuid>7f97c98d-8bec-474b-b84e-0d8b09ca3a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>c6d07555-595e-4de0-9919-fa624e868823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[21]/following::a[1]</value>
      <webElementGuid>f6aa03a7-d79d-4625-95a3-1c25a878b514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[20]/following::a[1]</value>
      <webElementGuid>fae582f2-b698-4fac-93a1-d85c8c5e134f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[5]</value>
      <webElementGuid>4d3b6738-6589-4ece-a865-a6486b404b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[5]</value>
      <webElementGuid>d80379f4-1e47-4f23-be17-699435d54302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>477c425b-28dc-4829-bf86-f516fc57593b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div[2]/div[2]/div/div/div/span/a</value>
      <webElementGuid>cc257096-5152-4198-8ac7-4ed25a52d878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'e9a15c51-ff54-41cd-be89-a295cf3324df_27984355-7420-4f86-bf52-e44cb8ce6c2a' and @name = 'btn.save' and @href = '#' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>7b5c0e78-56b6-414b-a16b-c0bb30b9d713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
