<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pafos_base2 base1 ajaxLoader modal-element</name>
   <tag></tag>
   <elementGuidId>704b418e-c862-4e00-84ff-1bc3af74f1e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1bccc59c-b315-7ad2-2217-3c4ead585760']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.base2.base1.ajaxLoader.modal-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8ede095-c66f-4a69-860b-6dbe9adf7126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base2 base1 ajaxLoader modal-element</value>
      <webElementGuid>28e681c5-8dcc-411f-a8ca-5ecfa2ddfcff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1bccc59c-b315-7ad2-2217-3c4ead585760&quot;)/div[@class=&quot;base2 base1 ajaxLoader modal-element&quot;]</value>
      <webElementGuid>290ec2b6-6784-40fc-9fa8-094298c1003b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1</value>
      <webElementGuid>e1474232-ed16-483c-9f3a-9b7b95985805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1bccc59c-b315-7ad2-2217-3c4ead585760']/div</value>
      <webElementGuid>f9a3de90-0e0f-4d98-8071-fbb975af73a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>008ad61e-d55c-4ecd-b76f-604e64057442</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
