<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Check Application Status_frame-content</name>
   <tag></tag>
   <elementGuidId>fbb2abf1-0dd7-4152-961d-c96f2c92e316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.frame-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fec09691-cd5d-4ae5-ae2a-579d3a4f07de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>1c70c7ca-3daa-4031-a500-c53cce914f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frame-content</value>
      <webElementGuid>f2ae82cf-7806-46a3-9a6e-3e7e0676e36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.Application.ApplicationInformation.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=201&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11</value>
      <webElementGuid>1c67d5ab-1f61-46e9-9794-89da3cf7063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>333ca3d6-d211-42c4-b3b2-16edfbc2a233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;rc-scrollbars-container sc-hAZoDl eayMnQ&quot;]/div[@class=&quot;rc-scrollbars-view&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;sc-kLLXSd gXmOZA frame-container&quot;]/iframe[@class=&quot;frame-content&quot;]</value>
      <webElementGuid>d8967f05-0d41-44e8-a990-5fbf677ced5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='']</value>
      <webElementGuid>9300b771-7c76-4365-9cd7-8a17d8cad54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/section/main/section/main/div/div/iframe</value>
      <webElementGuid>f23dd8f8-1546-4106-81ca-c0a28eb2f7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8f017fae-889c-4449-98ab-1d2eca8b80ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Application' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.Application.ApplicationInformation.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=201&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11']</value>
      <webElementGuid>4fd30443-e70e-4675-92c0-5e9ada4c0373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
