<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Check Application Status_frame-content_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>82088ec8-186d-4ea2-804e-26009ce83152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.frame-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>75f6128f-346f-482b-a5cf-748f86d8b00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Criminal Record</value>
      <webElementGuid>32cff887-b718-4a49-b790-cd8c0421959f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frame-content</value>
      <webElementGuid>ba992ea1-e573-46df-8563-7a682783ec8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.PIC.CriminalRecordWithDocuments.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=214&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11</value>
      <webElementGuid>10ea6095-ef36-43fe-a827-865d94a69aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c0a79a48-8c2e-4dd6-8aaf-4b522edaa302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;rc-scrollbars-container sc-hAZoDl eayMnQ&quot;]/div[@class=&quot;rc-scrollbars-view&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;sc-kLLXSd dqPFkY frame-container&quot;]/iframe[@class=&quot;frame-content&quot;]</value>
      <webElementGuid>1ed9849a-5bca-403f-bdba-7f95380c8564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='']</value>
      <webElementGuid>0a139561-42fa-4a0b-bab7-1ee0767295e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/section/main/section/main/div/div/iframe</value>
      <webElementGuid>07a0ce8a-992c-4c07-9458-91b37974dabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d3edc312-8eef-498f-bf3c-112c7ef07b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Criminal Record' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.PIC.CriminalRecordWithDocuments.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=214&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11']</value>
      <webElementGuid>2af2cd5e-a262-4564-a1b3-9ef01ff85092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
