<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Check Application Status_frame-content_1_2_3</name>
   <tag></tag>
   <elementGuidId>8e65be67-9e9a-457f-bfa3-7b8af3f7ca4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.frame-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d9aff801-469f-4ed1-8015-2742b0b0ac79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Employment Details</value>
      <webElementGuid>9b5b1c77-0848-4661-a481-ebdd89cc6de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frame-content</value>
      <webElementGuid>f7f602fa-eec4-4fe1-b727-86c136744e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.PIC.EmploymentDetails.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=213&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11</value>
      <webElementGuid>349ff698-af49-494a-ae37-ed7423a93f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6429105e-56bc-4285-b83c-1f8981248428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;rc-scrollbars-container sc-hAZoDl eayMnQ&quot;]/div[@class=&quot;rc-scrollbars-view&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;sc-kLLXSd gXmOEa frame-container&quot;]/iframe[@class=&quot;frame-content&quot;]</value>
      <webElementGuid>6e63f738-2d1b-4879-b211-8dd2bfd3b322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='']</value>
      <webElementGuid>e124f438-2edb-4ea7-8c75-a89e4a01d143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/section/main/section/main/div/div/iframe</value>
      <webElementGuid>424ce31e-abba-45a9-b91f-2ae8e1ea035b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f33be4c2-952a-4c78-a827-dbfb0ec65f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Employment Details' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.PIC.EmploymentDetails.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=213&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11']</value>
      <webElementGuid>238b4967-7aba-4e77-8c5b-e94482668266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
