<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Check Application Status_frame-content_1</name>
   <tag></tag>
   <elementGuidId>735ab233-3d07-4e2e-bf77-37b405ce2e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.frame-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>01baba13-e5c6-407f-bdcf-9b0bea6b7c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Person In Charge Details</value>
      <webElementGuid>82095220-ddc6-45f9-9c94-ad1fbadc5c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frame-content</value>
      <webElementGuid>e95c915c-1ec3-40df-bd59-1110a46007a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.PIC.PersonInChargeDetails.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=211&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11</value>
      <webElementGuid>7308c55d-dcc2-44f4-b1d6-191d33ba8c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1ea525d1-4d86-4303-82a5-8e30e9c796eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;rc-scrollbars-container sc-hAZoDl eayMnQ&quot;]/div[@class=&quot;rc-scrollbars-view&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;sc-kLLXSd gXmPJf frame-container&quot;]/iframe[@class=&quot;frame-content&quot;]</value>
      <webElementGuid>43d40866-517e-4201-bfca-12072d48d5c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='']</value>
      <webElementGuid>d8994e72-4821-4412-8f03-38e369b326d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/section/main/section/main/div/div/iframe</value>
      <webElementGuid>6eab4c78-ebef-477b-8c69-32b3eb87d9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bf66c270-67a7-46cb-8c5f-40716d52ac24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Person In Charge Details' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.PIC.PersonInChargeDetails.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=211&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11']</value>
      <webElementGuid>05ac5fa6-e320-4ad9-87ce-6ad052e60667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
