<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Check Application Status_frame-content_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>03622d98-d6e0-4ac3-ba1c-544ec6710956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.frame-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3539cb05-d24e-4483-8b5b-b3ec4a0ec63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Processing of Personal Data</value>
      <webElementGuid>b750b7f3-abc2-45f0-b6a0-63382d4ed0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frame-content</value>
      <webElementGuid>b2ff1793-12bd-46d1-8821-23f64dbceb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.Declaration.Declaration.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=221&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11</value>
      <webElementGuid>1a192610-37fb-4755-b1e7-4656d3636a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0149a6bf-5429-4bcf-a9a4-dd89205059a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;rc-scrollbars-container sc-hAZoDl eayMnQ&quot;]/div[@class=&quot;rc-scrollbars-view&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;sc-kLLXSd gXmPKZ frame-container&quot;]/iframe[@class=&quot;frame-content&quot;]</value>
      <webElementGuid>3d3ca784-c9dd-4bd1-8158-7b33387ad61e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='']</value>
      <webElementGuid>1a5fe4d1-483b-4460-a068-32ae50b918c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/section/main/section/main/div/div/iframe</value>
      <webElementGuid>9a0a3fb0-74ff-4a31-8ff1-c82a5d3e9b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>12c68123-9e83-4e22-92ce-8cf4c73f3fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Processing of Personal Data' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.Licensing.PIC.Declaration.Declaration.External/?Language=en-US&amp;pApplicationFormTypeCode=PersonInCharge&amp;pApplicationReferenceNumber=DRF-31842&amp;pBusinessEntityId=454&amp;pInternal=True&amp;pState=&amp;SerialNo=&amp;pProcess=&amp;SN=&amp;pDebug=false&amp;pFormSectionId=221&amp;pH1=Application Reference Number:&amp;pH2=DRF-31842&amp;pH3=Person in Charge&amp;CurrentUserLoginName=Pan11']</value>
      <webElementGuid>9a32993b-0ab3-4876-a84e-552a9d4d8f12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
