<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Telephone</name>
   <tag></tag>
   <elementGuidId>cb92a0ba-0831-4ba0-8429-1c83af48cdc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='8c1f55aa-bf65-4995-b61d-7fbe34dc69e5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8c1f55aa-bf65-4995-b61d-7fbe34dc69e5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>878f94f3-81c7-42b8-a5da-5c6cbc2d99e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8c1f55aa-bf65-4995-b61d-7fbe34dc69e5</value>
      <webElementGuid>d2bb7e2c-9ee7-4281-ae11-3a60133c0e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layouttype</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>5952e14e-e599-4fd6-9acc-7408bb042bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>897f4352-7011-4581-8c9f-6fc846649312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-cell droptarget</value>
      <webElementGuid>5a6bf680-8f02-4af1-ac29-ba5b52d61aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb179363-3963-4e01-af66-62f941b87874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cell Cell1430</value>
      <webElementGuid>c60afc4b-b1d3-4c43-b5c0-044c1d6ddda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controltype</name>
      <type>Main</type>
      <value>Cell</value>
      <webElementGuid>54f0fb1c-58b7-4e24-b22d-c7f855ea7b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3845bfd4-f92e-408d-ab97-aca25abca273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2341919c-e064-4364-9444-a02d78bdce14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Telephone:*</value>
      <webElementGuid>df7af950-3e0f-4ad3-853b-4f4bf84d34d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8c1f55aa-bf65-4995-b61d-7fbe34dc69e5&quot;)</value>
      <webElementGuid>ae619564-b1d7-45ea-919b-db4a5dbec97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2</value>
      <webElementGuid>ef89508d-2b55-4319-a534-1cb632365150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8c1f55aa-bf65-4995-b61d-7fbe34dc69e5']</value>
      <webElementGuid>8749ffca-afb1-4517-b7ca-07d5d06760d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6966afbd-4402-4674-ba61-d9e34c6b504a_7de79671-a7a4-466e-9237-957274553be2_Table']/span[7]</value>
      <webElementGuid>fc3e9b1e-fb1c-4963-864f-2e13a2f05e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[9]/following::span[1]</value>
      <webElementGuid>0a6f2a96-aad8-4e58-9960-4419639f3495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agia Anna/Αγία Άννα'])[1]/following::span[3]</value>
      <webElementGuid>e637a092-8073-492f-9ad4-4aee2b258cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/div/span[7]</value>
      <webElementGuid>4a45691a-6c33-4bf0-b423-ccf0a8a4db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8c1f55aa-bf65-4995-b61d-7fbe34dc69e5' and @name = 'Cell Cell1430' and (text() = 'Telephone:*' or . = 'Telephone:*')]</value>
      <webElementGuid>e8d17618-a98d-47a3-a3ac-7534bfa57c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
