<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Passport Number</name>
   <tag></tag>
   <elementGuidId>2122629c-4808-447a-bded-3a9189787ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f29f98f8-aef1-46f1-ab3e-7cd7bef21a81</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='f29f98f8-aef1-46f1-ab3e-7cd7bef21a81']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de996b23-8f16-4c9d-b470-3a9f582c183b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f29f98f8-aef1-46f1-ab3e-7cd7bef21a81</value>
      <webElementGuid>7f8d5070-aca3-46f8-8df7-e9e4348421e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layouttype</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>54355853-ce52-49c7-8bc9-c65dce64220f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>42df2da4-cadd-4e8f-af34-5547e9a11f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-cell droptarget lastcellinrow lastrow</value>
      <webElementGuid>e3b9bd88-75c1-4d42-8199-ef07527ee3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>93e76460-9e0f-4a6a-87d5-43657d67271f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cell Cell1392</value>
      <webElementGuid>d7e3c5ba-aacf-44be-b526-e30e49ce71e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controltype</name>
      <type>Main</type>
      <value>Cell</value>
      <webElementGuid>a98e6a28-ffd9-43b9-b88e-21249806a4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>50985a9f-e599-483b-a62d-cd9e593c34ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f426d66-2d9b-4339-b4c1-5fef7479dd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passport Number:*</value>
      <webElementGuid>2c9a751e-85df-444e-b7d2-0ccebba28a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f29f98f8-aef1-46f1-ab3e-7cd7bef21a81&quot;)</value>
      <webElementGuid>78ed81a0-5b03-4876-8bc9-24706d3aa092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1</value>
      <webElementGuid>a081a1fb-2624-488f-8fec-5c221060e3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='f29f98f8-aef1-46f1-ab3e-7cd7bef21a81']</value>
      <webElementGuid>a0ecbf16-0296-4114-b1de-d06626b5adfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='617b7581-a7a0-481a-bb65-888c482e0116_b12588e8-b77f-43ce-b42e-b7236da7e6a5_Table']/span</value>
      <webElementGuid>8c97d19a-07a5-45cf-8b10-681343510cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[3]</value>
      <webElementGuid>0e98b217-fe76-4cf8-ba82-21691688ae60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Number:'])[1]/following::span[4]</value>
      <webElementGuid>8f89398d-44f2-43b5-9c60-ac71c7a77b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/div[2]/span</value>
      <webElementGuid>5470864a-d937-4aa8-97f1-4627ef01e779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Passport' or . = 'Passport')]</value>
      <webElementGuid>0842bfea-6a3f-4963-98e8-6ac7d7f68461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
