<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please record the Residence Address of_9e7b7d</name>
   <tag></tag>
   <elementGuidId>582c9007-c4a4-46a5-bf27-9026758d8417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='7cb05a76-dd91-4e53-adcf-1891ff6ea53d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7cb05a76-dd91-4e53-adcf-1891ff6ea53d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>954cc886-4e6d-435f-b7c0-3ba2731399ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7cb05a76-dd91-4e53-adcf-1891ff6ea53d</value>
      <webElementGuid>14684e13-7536-41b2-95a6-08e096b89c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layouttype</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>76a42b66-e5cd-4fce-9032-01f7b01ecf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ab2e51e2-b85f-4bda-a817-0acf16a9e489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-cell droptarget lastcellinrow</value>
      <webElementGuid>0d4a7ac0-47ab-47c2-bc14-58c9f36b5f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f225a2a1-a856-41c2-8787-8246c24cb6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cell Cell379</value>
      <webElementGuid>e512329b-55fb-4bd8-ac86-29a1b031599f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controltype</name>
      <type>Main</type>
      <value>Cell</value>
      <webElementGuid>4e25ac14-9057-4742-a708-6fd598003a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e082265d-4a33-4e23-b86a-c7ee22cc9018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a3d1c143-6e6f-4476-a934-1faa35484a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please record the Residence Address of Person in Charge Postal Code:*Select AddressAddress:*District:*Larnaka/Λάρνακας...Town:*Agia Anna/Αγία Άννα...Telephone:*FaxMobile Phone:* </value>
      <webElementGuid>728d9bbf-9af4-4cab-8028-0465daadefc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7cb05a76-dd91-4e53-adcf-1891ff6ea53d&quot;)</value>
      <webElementGuid>2062c9a0-cbcd-4fb7-9f05-137556765079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2</value>
      <webElementGuid>60dbbfb2-d6a7-4114-aa12-c07c8605f6fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='7cb05a76-dd91-4e53-adcf-1891ff6ea53d']</value>
      <webElementGuid>8d30c060-5b9f-4edd-97f7-fd96e6c5350a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6966afbd-4402-4674-ba61-d9e34c6b504a_3f9c6274-16c2-40d0-bd80-5685a08e7c2b_Table']/span[5]</value>
      <webElementGuid>30186bd4-ab30-4ae1-8079-8a308cf4952a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original Data'])[2]/following::span[2]</value>
      <webElementGuid>abaeb253-7d5a-4ab2-a431-76258f12d3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[2]/following::span[7]</value>
      <webElementGuid>ae865c34-e407-4ef9-a1e4-25561a578856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[5]</value>
      <webElementGuid>7007b1de-f22b-4fc5-800d-ba020bda9898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '7cb05a76-dd91-4e53-adcf-1891ff6ea53d' and @name = 'Cell Cell379' and (text() = 'Please record the Residence Address of Person in Charge Postal Code:*Select AddressAddress:*District:*Larnaka/Λάρνακας...Town:*Agia Anna/Αγία Άννα...Telephone:*FaxMobile Phone:* ' or . = 'Please record the Residence Address of Person in Charge Postal Code:*Select AddressAddress:*District:*Larnaka/Λάρνακας...Town:*Agia Anna/Αγία Άννα...Telephone:*FaxMobile Phone:* ')]</value>
      <webElementGuid>ced867a8-2a7e-495c-a57c-32a846f13b69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
