<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes</name>
   <tag></tag>
   <elementGuidId>5a6aefa9-3430-403d-ba37-1824e2f76a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='eaf4041f-c9ca-47f5-9734-47547e2ee6ac_a6acdff2-a678-4b1a-b7fc-39dff25018a6_radioButtonItem_0_base']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eaf4041f-c9ca-47f5-9734-47547e2ee6ac_a6acdff2-a678-4b1a-b7fc-39dff25018a6_radioButtonItem_0_base > span.input-control-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>23cec431-7d2e-45cc-ba70-38ab534024d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-control-text</value>
      <webElementGuid>7f28bb05-3d39-49dd-b017-fd0ac36f5ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>3a070244-8cd6-4ccb-a306-9e6327648ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eaf4041f-c9ca-47f5-9734-47547e2ee6ac_a6acdff2-a678-4b1a-b7fc-39dff25018a6_radioButtonItem_0_base&quot;)/span[@class=&quot;input-control-text&quot;]</value>
      <webElementGuid>14e0f537-b3cf-4666-9b71-48b6456b969f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2_3_4</value>
      <webElementGuid>d4fea098-4f5f-4681-aa17-a1771dd225b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='eaf4041f-c9ca-47f5-9734-47547e2ee6ac_a6acdff2-a678-4b1a-b7fc-39dff25018a6_radioButtonItem_0_base']/span[2]</value>
      <webElementGuid>e0884f8b-663c-4686-b050-278261e843a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::span[6]</value>
      <webElementGuid>fb227a4e-8e34-4794-8932-c974016f98b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the applicant have a clean criminal record?'])[1]/following::span[7]</value>
      <webElementGuid>6ce679e3-4932-413f-8ed1-1b9b28982224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[2]</value>
      <webElementGuid>a8c83baa-3021-4d4a-81af-faf4e62c3810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[3]/preceding::span[3]</value>
      <webElementGuid>a0dddb66-1935-4cf5-848a-ea9cf4fa6ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>d8a989c4-8a1a-4f1c-8a47-0fa78324faa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/div[2]/div[2]/div/div/div/div/label/span[2]</value>
      <webElementGuid>ed122bbe-320e-41a5-8b0e-3966838ac9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>2ed7f974-e7e3-43e1-8e57-2f677f111fa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
