<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mobile Phone</name>
   <tag></tag>
   <elementGuidId>e858e6a9-e2ca-4e34-87d3-aadbd9e68c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='9dcf911b-a6c9-4421-ad34-64215680797f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9dcf911b-a6c9-4421-ad34-64215680797f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cadf2449-fd04-4b5d-99fd-e5028a44547f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9dcf911b-a6c9-4421-ad34-64215680797f</value>
      <webElementGuid>44b28fa5-5451-494f-be78-fd7e5574e1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layouttype</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>f5e84959-d3b7-41c8-a1fd-a5c59a3543b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>743b87be-4c0c-4f33-a8d7-cf9af0a68215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-cell droptarget lastrow</value>
      <webElementGuid>8137d215-ffdf-47e2-80c1-52d429c634bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4bd9989-c755-4b11-a91a-3a5ac23274e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cell Cell1433</value>
      <webElementGuid>371e98f2-0649-4275-93c0-d8835f3fa0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controltype</name>
      <type>Main</type>
      <value>Cell</value>
      <webElementGuid>ac02d50e-bad6-432a-93cd-9fdf577b831c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f1d24b54-8169-4494-b762-09f55fb7020c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>658b84e0-7dd7-4cd8-9acd-36680e6e5e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile Phone:*</value>
      <webElementGuid>39abb5c1-3445-4a8c-a43f-67c451b59af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9dcf911b-a6c9-4421-ad34-64215680797f&quot;)</value>
      <webElementGuid>42030ae0-345f-42f8-94e7-214027d68fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2</value>
      <webElementGuid>b98264a7-707a-46c3-a663-72600b0b4840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='9dcf911b-a6c9-4421-ad34-64215680797f']</value>
      <webElementGuid>f22c127d-2c40-4fe7-a25d-423a3075979f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6966afbd-4402-4674-ba61-d9e34c6b504a_7de79671-a7a4-466e-9237-957274553be2_Table']/span[9]</value>
      <webElementGuid>df71a990-a496-47d7-b343-f0c7eaafd0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fax'])[1]/following::span[3]</value>
      <webElementGuid>165a066c-6124-41ba-a7c3-848c9c3777a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::span[7]</value>
      <webElementGuid>68a7e64f-b9ae-430d-b2d1-cccfae96173a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/div/span[9]</value>
      <webElementGuid>b5a3f049-e45f-4263-8093-bbba0bea024a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '9dcf911b-a6c9-4421-ad34-64215680797f' and @name = 'Cell Cell1433' and (text() = 'Mobile Phone:*' or . = 'Mobile Phone:*')]</value>
      <webElementGuid>d07c901b-4a29-4023-b337-cb5f450ebce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
