<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Documents  Documents VisibilityUpdateO_a95a02</name>
   <tag></tag>
   <elementGuidId>095fb3df-f94e-42f8-ad3d-ca3bfda14f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='9f3be3a1-7b37-4763-a048-af4d136fca76']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9f3be3a1-7b37-4763-a048-af4d136fca76</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68551279-d112-434e-9bd3-d731b79d6239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9f3be3a1-7b37-4763-a048-af4d136fca76</value>
      <webElementGuid>f6756bf7-73d5-4618-8985-f5482e6cec81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layouttype</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>11257c54-0502-4b5b-8dcc-523df38460d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e48d10ad-b065-4bb2-8503-3aa7a031c612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-cell droptarget lastcellinrow</value>
      <webElementGuid>a5359dd5-e8ee-4919-974b-9ef4bfb565c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0ced4cb1-c6a5-4b06-84fa-03cf5d6642aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cell Cell1261</value>
      <webElementGuid>83ae1d8e-a0a0-4f2b-993b-3d0b28cff53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controltype</name>
      <type>Main</type>
      <value>Cell</value>
      <webElementGuid>7b2d479d-ec84-45cb-9c42-39c3c6a02453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2963bcbd-c5ed-4e4f-bf2f-cd55172eb572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d197e175-6917-4abc-870e-f8bda5907c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documents  Documents VisibilityUpdateOriginal Data</value>
      <webElementGuid>2dce5e0c-c053-4722-b645-50a9dce5ae2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9f3be3a1-7b37-4763-a048-af4d136fca76&quot;)</value>
      <webElementGuid>3c009ef2-b2ea-4f48-b781-854694e30615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/PIC/Page_NBA/iframe_Check Application Status_frame-content_1_2</value>
      <webElementGuid>d3b155a8-67e8-459f-9549-0fe6a7693a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='9f3be3a1-7b37-4763-a048-af4d136fca76']</value>
      <webElementGuid>8abac9c6-ff1c-47f6-b938-db9027fcd0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6966afbd-4402-4674-ba61-d9e34c6b504a_3f9c6274-16c2-40d0-bd80-5685a08e7c2b_Table']/span[10]</value>
      <webElementGuid>3fc361c9-6cea-43bf-9fcb-6928978fa1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[5]/following::span[1]</value>
      <webElementGuid>b882cf9c-f379-493e-9865-9b2bda0bbf97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::span[12]</value>
      <webElementGuid>f9f8b74b-d60a-47da-af03-84fa83c324ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[10]</value>
      <webElementGuid>a88a2ba5-a864-4719-a1bd-e7a21c34fc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '9f3be3a1-7b37-4763-a048-af4d136fca76' and @name = 'Cell Cell1261' and (text() = 'Documents  Documents VisibilityUpdateOriginal Data' or . = 'Documents  Documents VisibilityUpdateOriginal Data')]</value>
      <webElementGuid>9b16f290-9e8b-482b-bb30-fb053d7aac06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
