<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit</name>
   <tag></tag>
   <elementGuidId>588aa083-e59a-4f8d-b94b-046b245ba223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>665043f9-4bb1-4e16-aec3-818213b14358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85</value>
      <webElementGuid>0994162b-50a7-4b9d-96c1-df2491537ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn.submit</value>
      <webElementGuid>f6d67dc8-ca01-42fa-b4bc-cf20d8c8d8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SFC SourceCode-Forms-Controls-Web-Button visible</value>
      <webElementGuid>0d60c2a7-93f2-4e16-9617-13d7516e0e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c4972dc4-c8d4-4d75-adad-d200efc12278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9ac78fe-c2b8-4062-830f-9c4e178aa495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;isvisible&quot;:false,&quot;style&quot;:&quot;\u003cStyles\u003e\u003cStyle IsDefault=\&quot;True\&quot;\u003e\u003cMargin\u003e\u003cDefault\u003e3px\u003c/Default\u003e\u003c/Margin\u003e\u003c/Style\u003e\u003c/Styles\u003e&quot;}</value>
      <webElementGuid>d2519568-729e-46ef-81a6-d0d2735e5628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>8d242f78-d7df-4232-81ca-d8432b5149da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85&quot;)</value>
      <webElementGuid>fe593d8d-be93-45d8-94c5-78b7b4b00b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Contact Us Registered User/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>99cf20b2-aee8-4012-8134-f7c1284b02fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85']</value>
      <webElementGuid>1e579070-6a09-4b22-ae04-94edaf8f506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='1efff9ff-d3c3-61aa-b430-98ff6200bd23']/a</value>
      <webElementGuid>c5eadcc1-e371-40eb-9124-10c8a84df78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Submit')]</value>
      <webElementGuid>1c3b37e1-2da9-441a-9504-390846c80466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[3]/following::a[2]</value>
      <webElementGuid>ab1fc948-fc7b-4670-9540-21890aa4949b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[2]/following::a[2]</value>
      <webElementGuid>cecb788b-4d5a-4ae1-a878-e8f445cf1482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::a[4]</value>
      <webElementGuid>8dbed168-5f9e-4735-a6bb-4162c078dc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExternalUserRoleContactPerson'])[1]/preceding::a[4]</value>
      <webElementGuid>389ab48a-602f-41d0-9f75-68738684fa5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>985d3237-9fdb-4f03-a9cd-21206e9dddeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>1998a396-fb00-409c-a692-6d85fd0b09e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>269f54af-9bfb-409c-ad53-cc75213cd430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '26e53c11-fd80-bf0a-e46d-51e26b6278c0_286725f8-ee17-3bc5-6142-b060c4031e85' and @name = 'btn.submit' and @href = '#' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>1659684d-02a5-4194-87b6-cd9553e7f2b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
