<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Send Contact Us_frame-content</name>
   <tag></tag>
   <elementGuidId>d5aebed6-b4e9-45d0-bb63-7a0e48442c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.frame-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8d686ea1-ea29-48e0-9714-ba8689a78768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Send Contact Us</value>
      <webElementGuid>67568795-fab4-4cd2-aee4-64df29bae53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frame-content</value>
      <webElementGuid>fd0909d5-ec7a-4346-beb2-40e26c365b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.ContactUs.External/?Language=en-US&amp;CurrentUserLoginName=Pan11</value>
      <webElementGuid>1548d7d7-1763-4a14-8e1c-4db57fadcf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d6d58409-eaa4-4872-80d2-0669efbaea9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;rc-scrollbars-container sc-hAZoDl eayMnQ&quot;]/div[@class=&quot;rc-scrollbars-view&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/section[@class=&quot;ant-layout sc-ksZaOG fkmLfx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;sc-kLLXSd dqMoyd frame-container&quot;]/iframe[@class=&quot;frame-content&quot;]</value>
      <webElementGuid>a9b54e86-75bf-4d71-9c8d-b20f486c58d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='']</value>
      <webElementGuid>bff57cec-0388-4f7c-bb3f-df4b9e96efc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/section/main/section/main/div/div/iframe</value>
      <webElementGuid>9c1a182a-9266-4266-8e24-d5566193d395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>de08d54d-14be-465e-aed3-f451b9357867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Send Contact Us' and @src = 'https://dk2.bssdev.local/RuntimeOnlineUsers/Runtime/Form/NBA2.0.ONL.ContactUs.External/?Language=en-US&amp;CurrentUserLoginName=Pan11']</value>
      <webElementGuid>25cc9423-b377-421c-88f4-2c19736042d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
