<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_</name>
   <tag></tag>
   <elementGuidId>4e63e1d7-4226-473d-9ef2-e19fb6e7ddc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_86aeafe2-81d9-42c9-bd84-b854d45d79b6_FilePanel > label.file-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_86aeafe2-81d9-42c9-bd84-b854d45d79b6_FilePanel']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7c4fb4b7-f484-4b1e-bb13-2af0a5f1b9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_86aeafe2-81d9-42c9-bd84-b854d45d79b6_file-inputId</value>
      <webElementGuid>fccb47af-8240-4800-9c05-bcfc1942e7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-label</value>
      <webElementGuid>bd0a41c6-cad3-469e-94db-0898b63dcfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>facbd6d3-d252-4d46-8a5f-fe4d9239b6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_86aeafe2-81d9-42c9-bd84-b854d45d79b6_FilePanel&quot;)/label[@class=&quot;file-label&quot;]</value>
      <webElementGuid>940c67fd-45a5-4eca-be14-a384e167a7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Contact Us Registered User/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>d2c188da-719e-484c-bbf5-0367fd10e535</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_86aeafe2-81d9-42c9-bd84-b854d45d79b6_FilePanel']/label</value>
      <webElementGuid>2c9b8e62-45ca-491f-9bc8-a3940bbe4b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[2]/following::label[1]</value>
      <webElementGuid>ab6744d0-dbb9-414b-9eeb-b5394f33e1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Name'])[2]/following::label[1]</value>
      <webElementGuid>064a55d5-a36d-47da-85ac-d386f10042bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to attach a file'])[3]/preceding::label[1]</value>
      <webElementGuid>9e26fd84-381a-4453-87cf-4f7b6cd94627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL USER AUTHORIZATION'])[1]/preceding::label[2]</value>
      <webElementGuid>1d820533-4f29-44bb-aa1a-cb9805763b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/label</value>
      <webElementGuid>054a7001-92f5-45af-90fd-64d25c7d5c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>8c2d102d-8598-4282-bdd6-05224db4bad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
