<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>ec5669c8-f29f-4978-a797-12012aa22cd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_f335fa43-a03b-4ea2-a594-61eb521aec41_ToolbarButton > span.button-c > span.button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_f335fa43-a03b-4ea2-a594-61eb521aec41_ToolbarButton']/span[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd48cc3f-5a45-4498-bb29-392db8113436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-text</value>
      <webElementGuid>755de251-4e8f-4575-92e0-80aaa6d2eee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>9a39032f-41ea-4e24-8442-9a163d95fa8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_f335fa43-a03b-4ea2-a594-61eb521aec41_ToolbarButton&quot;)/span[@class=&quot;button-c&quot;]/span[@class=&quot;button-text&quot;]</value>
      <webElementGuid>1df01433-f0e5-4ab9-b9b6-9acabc25a234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NBA/Contact Us Registered User/Page_NBA/iframe_Send Contact Us_frame-content</value>
      <webElementGuid>2a89b69b-1946-483c-b47d-b7ae690d38cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='6bd13cd7-9563-e707-3f9d-f27b1a7fb1ec_f335fa43-a03b-4ea2-a594-61eb521aec41_ToolbarButton']/span[2]/span[2]</value>
      <webElementGuid>71ff1cab-2344-4eb3-ac2a-0734d486404b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[2]/following::span[5]</value>
      <webElementGuid>682d768a-c4b5-45f9-94cb-897e57638455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ActingAsTypeID_Business'])[1]/following::span[6]</value>
      <webElementGuid>fbed754a-98ea-46e5-b7c4-ef4f8365a4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::span[4]</value>
      <webElementGuid>66a3e54c-a187-4f5f-9f81-316a88836387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::span[9]</value>
      <webElementGuid>f116afbc-8292-418f-9603-1ae5c60dea6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>02ff461f-879f-483e-be42-fde8e17dbb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]/span[2]</value>
      <webElementGuid>19001d72-0fa0-41ea-8dab-b469a7e1da55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>5c68e464-8f30-4832-9818-00f2d0c8c39b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
